
/**
 * DO NOT EDIT THIS FILE DIRECTLY WITHOUT UPDATING THE BACKUP
 * A backup copy is stored at: lib/services/amazonService.bak.js
 *
 * Purpose:
 * - Centralized mappings from OpenWebNinja -> internal product shape
 * - Simple in-memory caching (configurable TTL via AMAZON_CACHE_TTL env, seconds)
 * - Price normalization utilities (price_value, price_display, currency)
 *
 * This file is intentionally defensive to avoid accidental regressions.
 */

const client = require('../openwebninjaClient');

const SEARCH_CACHE = new Map();
const PRODUCT_CACHE = new Map();
const CACHE_TTL = (Number(process.env.AMAZON_CACHE_TTL) || 90) * 1000; // default 90s

function cacheGet(map, key) {
  const entry = map.get(key);
  if (!entry) return null;
  if (Date.now() - entry.ts > CACHE_TTL) { map.delete(key); return null; }
  return entry.data;
}

function cacheSet(map, key, data) {
  map.set(key, { ts: Date.now(), data });
}

function normalizePrice(priceRaw) {
  if (priceRaw == null) return { price_display: 'N/A', price_value: null, currency: null };
  let s = String(priceRaw).replace(/\u00A0/g, ' ').trim(); // NBSP -> space
  // Extract currency symbols (€, £, $) if present
  const currencyMatch = s.match(/(€|EUR|EUR\.|EUR|GBP|£|\$|USD|EUR)/i);
  let currency = currencyMatch ? currencyMatch[0] : null;
  // Remove non-digit, non-sep characters except , and . and -
  let num = s.replace(/[^0-9,\.\-]/g, '').trim();
  if (!num) return { price_display: s, price_value: null, currency };
  // Detect european format like 1.234,56 -> remove dots then replace comma with dot
  if (num.indexOf(',') > -1 && num.indexOf('.') > -1 && num.indexOf('.') < num.indexOf(',')) {
    num = num.replace(/\./g, '').replace(/,/g, '.');
  } else if (num.indexOf(',') > -1 && num.indexOf('.') === -1) {
    num = num.replace(/,/g, '.');
  }
  const parsed = parseFloat(num);
  const price_value = Number.isFinite(parsed) ? parsed : null;
  return { price_display: s, price_value, currency };
}

function mapItem(owItem) {
  // Map common OpenWebNinja fields to our internal product shape
  const id = owItem.asin || owItem.ASIN || owItem.ct_asin || owItem.id || null;
  const title = owItem.product_title || owItem.title || owItem.ct_title || owItem.name || 'Prodotto';
  const rawPrice = owItem.ct_price || owItem.product_price || (owItem.price && (owItem.price.value || owItem.price.current_price)) || null;
  const priceData = normalizePrice(rawPrice);
  const currency = priceData.currency || owItem.ncy || owItem.currency || (owItem.price && owItem.price.currency) || null;
  const images = [];
  if (owItem.product_photos && Array.isArray(owItem.product_photos)) images.push(...owItem.product_photos);
  if (owItem.ct_photos && Array.isArray(owItem.ct_photos)) images.push(...owItem.ct_photos);
  if (owItem.product_photo) images.push(owItem.product_photo);
  if (owItem.ct_photo) images.push(owItem.ct_photo);
  if (owItem.image) images.push(owItem.image);
  // Deduplicate images
  const image = (images.filter(Boolean).map(String)).filter((v, i, a) => a.indexOf(v) === i)[0] || null;

  return {
    id,
    title,
    price_display: priceData.price_display,
    price_value: priceData.price_value,
    currency: currency,
    brand: owItem.ct_brand || owItem.brand || owItem.manufacturer || owItem.product_byline || 'N/A',
    rating: owItem.ct_star_rating || owItem.product_star_rating || owItem.rating || 'N/A',
    reviews_count: owItem.product_num_ratings || owItem.ct_num_ratings || owItem.reviews_count || null,
    original_price: owItem.product_original_price || owItem.ct_original_price || null,
    badges: {
      best_seller: !!owItem.is_best_seller,
      amazon_choice: !!owItem.is_amazon_choice,
      prime: !!owItem.is_prime,
      climate_pledge: !!owItem.climate_pledge_friendly,
      product_badge: owItem.product_badge || null
    },
    offers: {
      num_offers: owItem.product_num_offers || null,
      minimum_offer_price: owItem.product_minimum_offer_price || null
    },
    delivery: owItem.delivery || null,
    sales_volume: owItem.sales_volume || null,
    image,
    images: images.filter(Boolean).map(String),
    url: owItem.ct_url || owItem.product_url || owItem.url || null,
    details: owItem.ct_description || owItem.product_description || owItem.description || owItem.snippet || '',
    raw: owItem
  };
}

async function searchProducts(query, country = 'IT', page = 1, limit = 24, opts = {}) {
  const { category, min_price, max_price, sort } = opts || {};
  const key = `${query}|${country}|${page}|${limit}|${category||''}|${min_price||''}|${max_price||''}|${sort||''}`;
  const cached = cacheGet(SEARCH_CACHE, key);
  if (cached) return cached;

  const params = { query, country, page, limit };
  if (category) params.category = category;
  if (min_price != null) params.min_price = min_price;
  if (max_price != null) params.max_price = max_price;
  if (sort) params.sort = sort; // e.g., 'price_asc','price_desc','rating_desc'
  const resp = await client.get('/search', { params });
  const data = resp.data || {};
  // Support multiple shapes including nested data.products (as in OpenWebNinja responses)
  const list = data.results || data.items || data.products || (data.data && (data.data.products || data.data.items || data.data.results)) || data.data || data || [];
  const mapped = (Array.isArray(list) ? list : []).map(mapItem);
  cacheSet(SEARCH_CACHE, key, mapped);
  return mapped;
}

async function getProductByAsin(asin, country = 'IT') {
  const key = `p|${asin}|${country}`;
  const cached = cacheGet(PRODUCT_CACHE, key);
  if (cached) return cached;
  const params = { asin, country };
  try {
    const resp = await client.get('/product', { params });
    const data = resp.data || {};
    // OpenWebNinja may return the item directly or inside data.result
    const item = data.result || data.data || data.product || data || {};
    const mapped = mapItem(item);
    cacheSet(PRODUCT_CACHE, key, mapped);
    return mapped;
  } catch (error) {
    console.error(`Errore dettagli prodotto ${asin}:`, error.message);
    // Fallback: cerca il prodotto nella cache di ricerca o restituisci dati limitati
    const searchKey = Object.keys(SEARCH_CACHE).find(k => k.includes(asin));
    if (searchKey) {
      const searchResults = cacheGet(SEARCH_CACHE, searchKey);
      const product = searchResults?.find(p => p.id === asin);
      if (product) {
        console.log(`Usando dati dalla ricerca per ${asin}`);
        return product;
      }
    }
    // Se non trovato, restituisci un oggetto con dati minimi
    return {
      id: asin,
      title: 'Prodotto non disponibile',
      price_display: 'N/A',
      price_value: null,
      currency: null,
      brand: 'N/A',
      rating: 'N/A',
      reviews_count: null,
      original_price: null,
      badges: {},
      offers: {},
      delivery: null,
      sales_volume: null,
      image: null,
      images: [],
      url: null,
      details: 'Impossibile caricare i dettagli completi del prodotto. Potrebbe non essere disponibile nell\'API.',
      raw: { asin }
    };
  }
}

async function getPricing(asin, country = 'IT') {
  const params = { asin, country };
  const resp = await client.get('/pricing', { params });
  return resp.data || {};
}

function clearCache() { SEARCH_CACHE.clear(); PRODUCT_CACHE.clear(); }

module.exports = { searchProducts, getProductByAsin, getPricing, clearCache };
